package com.tsu.mobilegamelab4.game.map.firstlocation

enum class FirstLocationTileType {
    //first loc
    EMPTY, FLOOR_1, FLOOR_2, FLOOR_3, FLOOR_4, FLOOR_5, FLOOR_6, FLOOR_7, FLOOR_8, FLOOR_LADDER, FLOOR_SPIKES,
    WALL_BANNER_BLUE, WALL_BANNER_RED, WALL_BANNER_GREEN, WALL_BANNER_YELLOW, WALL, LEFT_CORNER_WALL, RIGHT_CORNER_WALL,
    WALL_SIDE_FRONT_LEFT, WALL_SIDE_FRONT_RIGHT, WALL_SIDE_LEFT, WALL_SIDE_RIGHT, WALL_SIDE_LEFT_CORNER, WALL_SIDE_RIGHT_CORNER, WALL_TOP, WALL_OUTSIDE_LEFT_CORNER, WALL_OUTSIDE_RIGHT_CORNER,
    FLOOR_STEPS_LU, FLOOR_STEPS_RU, WALL_GOO, WALL_FOUNTAIN_WATER, WALL_FOUNTAIN_LAVA, WALL_FOUNTAIN_TOP,
    FLOOR_STEPS_LB, FLOOR_STEPS_RB, FLOOR_GOO, FLOOR_FOUNTAIN_WATER, FLOOR_FOUNTAIN_LAVA,
    DOORS_FRAME_TOP_LEFT, DOORS_FRAME_TOP_RIGHT, COLUMN_TOP, WALL_COLUMN_TOP,
    DOORS_FRAME_LEFT_U, DOORS_LEAF_CLOSED_LU, DOORS_LEAF_CLOSED_RU, DOORS_FRAME_RIGHT_U, DOORS_LEAF_LU, DOORS_LEAF_RU, COLUMN_MID, WALL_COLUMN_MID,
    DOORS_FRAME_LEFT_B, DOORS_LEAF_CLOSED_LB, DOORS_LEAF_CLOSED_RB, DOORS_FRAME_RIGHT_B, DOORS_LEAF_LB, DOORS_LEAF_RB, COLUMN_BOTTOM, WALL_COLUMN_BOTTOM,
    CRATE_U, CHEST_CLOSED, CHEST_OPEN_EMPTY, CHEST_OPEN_FULL,
    CRATE_DOWN
}